version: '2.2'

networks:
  app:
    driver: bridge

services:
  db1:
    build:
      context: ./
      args:
        - APP=db1
    container_name: 'db1'
    links:
      - rabbitmq
    networks:
      - app
  db2:
    build:
      context: ./
      args:
        - APP=db2
    container_name: 'db2'
    links:
      - rabbitmq
    networks:
      - app
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '15672:15672'
      - '5672:5672'
    container_name: 'rabbitmq'
    networks:
      - app
